Fix minor warnings from rust 1.66.0 (#2018)
* Fix lint error in IT test

error: casting to the same type is unnecessary (`i64` -> `i64`)
   --> avro/tests/io.rs:135:64
    |
135 |         let encoded = to_avro_datum(&Schema::Long, Value::Long(*number as i64)).unwrap();
    |                                                                ^^^^^^^^^^^^^^ help: try: `*number`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_cast
    = note: `-D clippy::unnecessary-cast` implied by `-D clippy::all`

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

* Fix lint warning in rustdoc

warning: unclosed HTML tag `Value`
   --> avro/src/writer.rs:459:23
    |
459 |     /// Write the Into<Value> to the provided Write object. Returns a result with the number
    |                       ^^^^^^^
    |
    = note: `#[warn(rustdoc::invalid_html_tags)]` on by default
help: try marking as source code
    |
459 |     /// Write the `Into<Value>` to the provided Write object. Returns a result with the number
    |                   +           +

warning: `apache-avro` (lib doc) generated 1 warning

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

* Remove a non-existing label that dependabot tries to set when creating a PR

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>
(cherry picked from commit 5016cd5c3f2054ebacce7983785c228798e47f59)