Re-enable the Javadocs build
It is still broken due to:
```
Error:  Plugin org.apache.avro:avro-maven-plugin:1.13.0-SNAPSHOT or one of its dependencies could not be resolved:
Error:  	Could not find artifact org.apache.avro:avro-maven-plugin:jar:1.13.0-SNAPSHOT
Error:  -> [Help 1]
```

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>