[C++] g++ (GCC) 14.2.1 20240910 fails to compile due to -Werror=conversion (#3166)
* Fix error: conversion from ‘boost::crc_optimal<32, 79764919, 4294967295, 4294967295, true, true>::value_type’ {aka ‘long unsigned int’} to ‘uint32_t’ {aka ‘unsigned int’} may change value [-Werror=conversion]

* Fix error: ‘find_if’ is not a member of ‘std’;

* Fix error: no matching function for call to ‘find(std::vector<std::__cxx11::basic_string<char> >::const_iterator, std::vector<std::__cxx11::basic_string<char> >::const_iterator, const std::string&)’