NO_JIRA: [Rust] Fix new clippy lint error in Rust 1.77.0
```
    Checking apache-avro v0.17.0 (/home/martin/git/apache/avro/lang/rust/avro)
    Checking zstd v0.13.0
    Checking hello-wasm v0.1.0 (/home/martin/git/apache/avro/lang/rust/wasm-demo)
error: useless use of `vec!`
   --> avro/src/reader.rs:679:24
    |
679 |         let expected = vec![record1.into(), record2.into()];
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: you can use an array directly: `[record1.into(), record2.into()]`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_vec
    = note: `-D clippy::useless-vec` implied by `-D clippy::all`
    = help: to override `-D clippy::all` add `#[allow(clippy::useless_vec)]`

error: could not compile `apache-avro` (lib test) due to 1 previous error
```

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>
(cherry picked from commit 8866b81016816dc4a6b45027e02506783c4567fd)