Allow avro C to be built on musl based systems.
The type `ssize_t` is defined in sys/types.h, and nowhere else
in the musl standard C library, so it should be included for the
compilation to succeed.

This fixes several errors like:

    In file included from src/generic.c:29:0:
    src/generic.c: In function ‘avro_generic_value_new’:
    src/avro_generic_internal.h:63:39:
        error: ‘ssize_t’ undeclared (first use in this function);
               did you mean ‘size_t’?

Signed-off-by: Titouan Christophe <titouan.christophe@railnova.eu>