Drop support for Avro 1.9.0-1.10.2
Due to an incompatibility introduced in Avro 1.11.0

error: no suitable constructor found for SpecificRecordBuilderBase(Schema,SpecificData)