NO-JIRA: [Rust] Fix build errors with 1.78.0-nightly (0ecbd0605 2024-02-25)
Extract the test trait impls out of the test function body.
No user facing changes!

```
error: non-local `impl` definition, they should be avoided as they go against expectation
  --> avro/tests/validators.rs:42:5
   |
42 | /     impl SchemaNamespaceValidator for CustomValidator {
43 | |         fn validate(&self, _ns: &str) -> AvroResult<()> {
44 | |             Ok(())
45 | |         }
46 | |     }
   | |_____^
   |
   = help: move this `impl` block outside the of the current function `avro_3900_custom_validator_with_spec_invalid_names`
   = note: an `impl` definition is non-local if it is nested inside an item and neither the type nor the trait are at the same nesting level as the `impl` block
   = note: one exception to the rule are anon-const (`const _: () = { ... }`) at top-level module and anon-const at the same nesting as the trait or type
   = note: this lint may become deny-by-default in the edition 2024 and higher, see the tracking issue <https://github.com/rust-lang/rust/issues/120363>
```

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>
(cherry picked from commit 9e72af2593ceb76ccde7710408f1177635697ece)