AVRO-4032: Add tests for Codec::Null and ::Deflate
This way there is no need to enable other codecs when running unrelated tests.
Otherwise the build fails with:
```
error: function `avro_4032_codec_settings` is never used
  --> avro/tests/codecs.rs:50:4
   |
50 | fn avro_4032_codec_settings(codec: Codec) -> TestResult {
   |    ^^^^^^^^^^^^^^^^^^^^^^^^
```

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>